apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-hml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/feynoordy/igreja-platform-aws
    targetRevision: main
    path: k8s/apps/frontend/hml
  destination:
    server: https://kubernetes.default.svc
    namespace: igreja-hml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
